global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['flask_collector:8080']